# -*- coding: utf-8 -*-
"""HealthBeds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xz-JhbjXtlnrNwgYPLNnt0X9x7Qen3-p
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression as lr
from sklearn.model_selection import train_test_split as tts

df = pd.read_csv("healthdataset.csv")
df

a=df['Time_of_Stay'].mean()
a

y = df["Severity"].iloc[0:100]
x = df["Number_of_Visits"].head(100)
plt.xlabel("Visits",color="blue")
plt.ylabel("Severity",color="#9A4EAE")
plt.scatter(x,y,color="red")

"""We can conclude the following observations
*   The bracket of people from severity 0.6 to 0.8 had an average visits of 4-7times
*   The bracket of people from intensity 1 had no fixed or pattern like viits can be due to reasons like changing hospitals , early diagonosis etc
*   Whereas as intensity bracket of people from 0.2 to 0.6 had average visits of 1-4 times
*   We can conclude that the intensities depend somewhat on no. of visits



"""

y = df["Time_of_Stay"].iloc[0:100]
x = df["Severity"].head(100)
plt.xlabel("severity",color="blue")
plt.ylabel("time of stay",color="#9A4EAE")
plt.scatter(x,y,color="red")

"""

*   Using the graph above we can say from severities 0 to 0.9 as the severity grows , the time stay grows too
*   However time of stay is uneven which concludes that diseases like migraines require less bed time as patients are given vaccines due to which beds at intensity 1 prediction is difficult

"""

x = df[["Severity","Previous_Visits"]]
y = df["Time_of_Stay"]

x_train, x_test, y_train, y_test = tts(x,y,test_size=0.2)
model = lr()
model.fit(x_train,y_train)


y_test_pred = model.predict(x_test)

from sklearn.metrics import mean_squared_error

# Calculate the MSE
mse = mean_squared_error(y_test, y_test_pred)

print(f"Mean Squared Error: {mse:.2f}")

#Now for the exact part

# Get input from user
sev = float(input("Enter Severity (0-1): "))
visits = float(input("Enter number of Previous Visits: "))

# Reshape into the 2D format the model expects
user_input = [[sev, visits]]

result = model.predict(user_input)
print(f"The estimated Time of Stay is: {result[0]:.2f} days")